spring:
  application:
    name: ticketguard-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketguard
    username: postgres
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: mohitsmohit650@gmail.com
    password: ipia ulyt eybj dhgj

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 3e7dfb0b6d3cb0ef8d7b0b16df6a52fd8a6d82d2ef8f6e55a1b8e7f47c6a1234
  expiration: 86400000